---
title: "Lab2"
author: "Xiaochuan Rong"
date: "13/12/2021"
output: html_document
---

```{r}
library(psych) # for describe\t
library(tidyverse) # for tidy code and ggplot\t
library(cAIC4) # for cAIC\t
library(r2glmm) # for r2beta\t
library(lme4) # for lmer
library(lmerTest) # to get singificance test in lmer
library(MuMIn) # for r.squaredGLMM
library(readr)
library(dplyr)
```

```{r}
data_postoperative_pain_int<-read_csv("D:/Lund/R/work directory/Lab/surgery_data_A.csv")

library(DataExplorer)
DataExplorer::create_report(data_postoperative_pain_int)
str(data_postoperative_pain_int)
summary(data_postoperative_pain_int)
data_postoperative_pain_int %>% filter_all(any_vars(. %in% c("woman")))
data_postoperative_pain_int['sex'][data_postoperative_pain_int['sex'] == "woman"] <- "female"
hist(data_postoperative_pain_int$pain) 
```

```{r}
random_model_int=lmer(pain~age+sex+STAI_trait+pain_cat+cortisol_serum+
                       mindfulness+(1|hospital), 
                        data = data_postoperative_pain_int)
random_model_int
summary(random_model_int)
confint(random_model_int)
boxplot(pain ~ hospital, data = data_postoperative_pain_int)
```

```{r}
r2beta(random_model_int, method = "nsj", data = data_postoperative_pain_int)
r.squaredGLMM(random_model_int)
```

```{r}
pre_newdata<-predict(random_model_int, surgery_data_2, allow.new.levels=TRUE)
RSS=sum((surgery_data_2$pain-pre_newdata)^2)
RSS
mod_mean<-lm(pain~1, data = surgery_data_2)
TSS=sum((surgery_data_2$pain-predict(mod_mean))^2)
TSS
R2=1-(RSS/TSS)
R2
```

```{r}
new_random_model_int=lmer(pain~cortisol_serum+(1|hospital), 
                        data = data_postoperative_pain_int)
new_random_model_int
```

```{r}
new_random_model_slope=lmer(pain~cortisol_serum+(cortisol_serum|hospital), 
                        data = data_postoperative_pain_int)
new_random_model_slope
```
```{r}
data_postoperative_pain_int = data_postoperative_pain_int %>%
mutate(pred_int = predict(new_random_model_int), pred_slope=predict(new_random_model_slope))

data_postoperative_pain_int %>%
ggplot() + aes(y = pain, x = cortisol_serum, group = hospital) +
geom_point(aes(color = hospital), size = 2) + geom_line(color = "blue",
aes(y = pred_int, x = cortisol_serum)) + facet_wrap(~hospital,
ncol = 2)
```

```{r}
data_postoperative_pain_int %>%
ggplot() + aes(y = pain, x = cortisol_serum, group = hospital) +
geom_point(aes(color = hospital), size = 2) + geom_line(color = "blue",
aes(y = pred_slope, x = cortisol_serum)) + facet_wrap(~hospital,
ncol = 2)
```

```{r}
cAIC(new_random_model_int)$caic
cAIC(new_random_model_slope)$caic
anova(new_random_model_int, new_random_model_slope)
```

